### ISSUE TITLE
Arrow Navigation of Games in DojoBase

### ISSUE THREAD

**Issue by dprues** [jackstenglein/chess-dojo-scheduler#569]
It’s generally difficult to navigate the variations in an annotated game or opening file. The standard way of doing so, is, I think a good one. You press the forward arrow, and if there is more than one move, a dialogue pops up with all the moves (main move + variations). You then use up and down arrows to select the variation you want to go forward in. You can later use back arrows to rejoin the main line if you have gone down a variation.

**Comment by dprues** [comment]
Right now you can go forward and backwards with forward and backward arrows, but it always follows the mainline, and you can’t get into any variations, other than by finding them visually and clicking on them.

**Comment by jackstenglein** [comment]
@dprues In the viewer settings, change the `Variation Behavior` setting from `None` to `Prompt in Dialog`.

<img width="575" alt="Screenshot 2024-06-17 at 2 17 37 PM" src="https://github.com/jackstenglein/chess-dojo-scheduler/assets/22841845/d912dee9-78f0-48e9-ac58-0966f27feba4">

**Comment by dprues** [comment]
This is great! Can we:
1) Make this the default (ppl can switch to none, but everyone starts with this option)
2) Make the box smaller, and have it not block the board, so ppl can see the board when picking which variation to go down.
3) Remove text instructions and just offer the available moves. (This will help make this box much smaller).

**Comment by jackstenglein** [comment]
@dprues Sorry for the delay on this. I've set it to the default, and I've moved the instructions into a hover tooltip, which makes the box size much smaller:

<img width="1717" alt="Screenshot 2024-07-28 at 9 30 59 PM" src="https://github.com/user-attachments/assets/d0b3971e-4688-4b3a-8dd6-161a67f38369">

Finally, I've updated it so that it uses the following rules in order when positioning the dialog:
1. If there is enough space on the left side of the board, it gets centered in that area.
2. If there is enough space on the right side of the board, it gets centered in that area.
3. It gets centered in the screen.

I haven't pushed it to the prod site yet, but it should be live on the beta site now: https://beta.chessdojo.club

Could you test it out and let me know if you want any other changes before I push it to everyone?
