### ISSUE TITLE
When opening a game, set board orientation to the user who annotated the game by default

### ISSUE THREAD

**Issue by hellokostya** [jackstenglein/chess-dojo-scheduler#658]
Perhaps it could be changed in settings or something but would be great to get the annotator's POV when opening up a game, because it's not always clear who the annotator was.

**Comment by jackstenglein** [comment]
@hellokostya This already happens, if the user who uploaded the game set the default orientation

**Comment by jackstenglein** [comment]
@hellokostya I made an improvement to our backend code which automatically sets the orientation on new games if we can detect who is playing which color. So this will be most helpful for online games, where the username is already on the PGN.

Otherwise, we'll have to continue relying on them picking the orientation in the settings.
